name: font_rendering_error_example
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    # assets:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
#  fonts:
#    - family: Lato
#      fonts:
#        - asset: fonts/Lato-Regular.ttf
#    - family: Montserrat
#      fonts:
#        - asset: fonts/Montserrat-Regular.ttf
#
#    - family: Ubuntu
#      fonts:
#        - asset: fonts/Ubuntu-Regular.ttf
#    - family: TitilliumWeb
#      fonts:
#        - asset: fonts/TitilliumWeb-Regular.ttf
#    - family: StalinistOne
#      fonts:
#        - asset: fonts/StalinistOne-Regular.ttf
#    - family: SourceSansPro
#      fonts:
#        - asset: fonts/SourceSansPro-Regular.ttf
#    - family: SourceCodePro
#      fonts:
#        - asset: fonts/SourceCodePro-Regular.ttf
#    - family: Slabo27px
#      fonts:
#        - asset: fonts/Slabo27px-Regular.ttf
#    - family: RobotoCondensed
#      fonts:
#        - asset: fonts/RobotoCondensed-Regular.ttf
#    - family: Roboto
#      fonts:
#        - asset: fonts/Roboto-Regular.ttf
#    - family: PTSerif
#      fonts:
#        - asset: fonts/PTSerif-Regular.ttf
#    - family: PTSansNarrow
#      fonts:
#        - asset: fonts/PTSansNarrow-Regular.ttf
#    - family: PTSans
#      fonts:
#        - asset: fonts/PTSans-Regular.ttf
#    - family: Poppins
#      fonts:
#        - asset: fonts/Poppins-Regular.ttf
#    - family: Oxygen
#      fonts:
#        - asset: fonts/Oxygen-Regular.ttf
#    - family: OpenSans
#      fonts:
#        - asset: fonts/OpenSans-Regular.ttf
#    - family: NunitoSans
#      fonts:
#        - asset: fonts/NunitoSans-Regular.ttf
#    - family: Nunito
#      fonts:
#        - asset: fonts/Nunito-Regular.ttf
#    - family: NotoSerif
#      fonts:
#        - asset: fonts/NotoSerif-Regular.ttf
#    - family: NotoSans
#      fonts:
#        - asset: fonts/NotoSans-Regular.ttf
#    - family: NanumGothic
#      fonts:
#        - asset: fonts/NanumGothic-Regular.ttf
#    - family: Mukta
#      fonts:
#        - asset: fonts/Mukta-Regular.ttf
#    - family: Merriweather
#      fonts:
#        - asset: fonts/Merriweather-Regular.ttf
#    - family: Lobster
#      fonts:
#        - asset: fonts/Lobster-Regular.ttf
#    - family: LibreBaskerville
#      fonts:
#        - asset: fonts/LibreBaskerville-Regular.ttf
#    - family: LexendMega
#      fonts:
#        - asset: fonts/LexendMega-Regular.ttf
#    - family: LexendGiga
#      fonts:
#        - asset: fonts/LexendGiga-Regular.ttf
#    - family: Jomhuria
#      fonts:
#        - asset: fonts/Jomhuria-Regular.ttf
#    - family: IBMPlexSans
#      fonts:
#        - asset: fonts/IBMPlexSans-Regular.ttf
#    - family: HindSiliguri
#      fonts:
#        - asset: fonts/HindSiliguri-Regular.ttf
#    - family: Hanalei
#      fonts:
#        - asset: fonts/Hanalei-Regular.ttf
#    - family: HammersmithOne
#      fonts:
#        - asset: fonts/HammersmithOne-Regular.ttf
#    - family: FjallaOne
#      fonts:
#        - asset: fonts/FjallaOne-Regular.ttf
#    - family: FiraSans
#      fonts:
#        - asset: fonts/FiraSans-Regular.ttf
#    - family: CrimsonText
#      fonts:
#        - asset: fonts/CrimsonText-Regular.ttf
#    - family: BigShouldersDisplay
#      fonts:
#        - asset: fonts/BigShouldersDisplay-Regular.ttf
#    - family: Benne
#      fonts:
#        - asset: fonts/Benne-Regular.ttf
#    - family: BebasNeue
#      fonts:
#        - asset: fonts/BebasNeue-Regular.ttf
#    - family: Barlow
#      fonts:
#        - asset: fonts/Barlow-Regular.ttf
#    - family: Anton
#      fonts:
#        - asset: fonts/Anton-Regular.ttf
#    - family: Abel
#      fonts:
#        - asset: fonts/Abel-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
